name: Release Linux

on:
  push:
    tags:
      - 'v*'       # 推送 tag v1.2.3 触发

permissions:
  contents: write   # 允许创建 Release

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build Linux packages
        run: npm run tauri build
        # 产物路径: src-tauri/target/release/bundle/{deb,appimage}

      - name: Upload Linux release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            src-tauri/target/release/bundle/deb/*.deb
            src-tauri/target/release/bundle/appimage/*.AppImage
        env:
          GITHUB_TOKEN: ${{ secrets.My_GITHUB_TOKEN }}
