name: Release macOS

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Install extra tools
        run: brew install create-dmg

      - name: Build macOS packages
        run: npm run tauri build
        # 产物路径: src-tauri/target/release/bundle/dmg/*.dmg

      - name: Upload macOS release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            src-tauri/target/release/bundle/dmg/*.dmg
            src-tauri/target/release/bundle/macos/*.app
        env:
          GITHUB_TOKEN: ${{ secrets.My_GITHUB_TOKEN }}
